language: python
matrix:
    include:
        - os: linux
          sudo: required
          python: 3.4
          env: TOXENV=py34
        - os: linux
          sudo: required
          python: 3.5
          env: TOXENV=py35
        - os: linux
          sudo: required
          python: 3.6
          env: TOXENV=py36
        - os: osx
#          language: generic
          python: 3.4
          env: TOXENV=py34
        - os: osx
#          language: generic
          python: 3.4
          env: TOXENV=py35
        - os: osx
#          language: generic
          python: 3.4
          env: TOXENV=py36
#python:
#  - "3.4"
#  - "3.5"
#  - "3.6"

# command to install dependencies
install:
  - "pip install ."
  - "pip install -r requirements.txt"
# command to run tests
script: python setup.py test
